---
- name: Create Ceph pool on first active storage node
  hosts: all
  gather_facts: false
  vars:
    pool_name: rbd
  tasks:
    - name: Get all storage nodes from inventory
      set_fact:
        storage_nodes: "{{ groups['storage'] | default([]) }}"
      
    - name: Check microceph cluster status on storage nodes
      shell: microceph cluster list
      register: cluster_status
      delegate_to: "{{ item }}"
      loop: "{{ storage_nodes }}"
      failed_when: false
      changed_when: false
      
    - name: Parse cluster status and find active nodes
      set_fact:
        active_storage_nodes: >-
          {{
            active_storage_nodes | default([]) +
            [item.item] if (
              item.rc == 0 and
              'ONLINE' in item.stdout
            ) else active_storage_nodes | default([])
          }}
      loop: "{{ cluster_status.results }}"
      when: item.item in storage_nodes
      
    - name: Fail if no active storage nodes found
      fail:
        msg: "No active storage nodes found in microceph cluster"
      when: active_storage_nodes | default([]) | length == 0
      
    - name: Set first active storage node
      set_fact:
        target_node: "{{ active_storage_nodes[0] }}"
        
    - name: Check if pool already exists
      shell: microceph.ceph osd pool ls | grep -w "{{ pool_name }}"
      register: pool_exists
      delegate_to: "{{ target_node }}"
      failed_when: false
      changed_when: false
      
    - name: Create pool if it doesn't exist
      shell: microceph.ceph osd pool create "{{ pool_name }}"
      delegate_to: "{{ target_node }}"
      when: pool_exists.rc != 0
      register: pool_creation
      
    - name: Initialize RBD on the pool
      shell: rbd pool init "{{ pool_name }}"
      delegate_to: "{{ target_node }}"
      when: pool_exists.rc != 0 or pool_creation is changed
      register: rbd_init
      failed_when: false
      
    - name: Display result
      debug:
        msg: >-
          {% if pool_exists.rc == 0 %}
          Pool '{{ pool_name }}' already exists on {{ target_node }}. RBD initialization attempted.
          {% else %}
          Pool '{{ pool_name }}' created successfully on {{ target_node }}. RBD initialized.
          {% endif %}
