---
- name: Install rathole configuration and service
  hosts: core
  become: yes
  vars:
    rathole_binary_path: "/usr/local/bin/rathole"

  tasks:
    - name: Check if rathole binary exists on ansible host
      stat:
        path: /usr/local/bin/rathole
      register: rathole_binary_ansible_host
      delegate_to: localhost

    - name: Fail if rathole binary not found
      fail:
        msg: "Rathole binary not found. Please run build-rathole.yml first."
      when: not rathole_binary_ansible_host.stat.exists

    - name: Copy rathole binary from ansible host
      copy:
        src: /usr/local/bin/rathole
        dest: "{{ rathole_binary_path }}"
        mode: '0755'
        owner: root
        group: root

    - name: Create rathole config directory
      file:
        path: /etc/rathole
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: Install rathole client config template
      copy:
        src: rathole-client-config.toml.j2
        dest: /etc/rathole/client-config.toml.j2
        mode: '0644'
        owner: root
        group: root

    - name: Install rathole SSH client config template
      copy:
        src: rathole-ssh-client-config.toml.j2
        dest: /etc/rathole/ssh-client-config.toml.j2
        mode: '0644'
        owner: root
        group: root

    - name: Create rathole client startup script
      copy:
        src: rathole-client-start
        dest: /usr/local/bin/rathole-client-start
        mode: '0755'
        owner: root
        group: root

    - name: Create rathole SSH client startup script
      copy:
        src: rathole-ssh-client-start
        dest: /usr/local/bin/rathole-ssh-client-start
        mode: '0755'
        owner: root
        group: root

    - name: Create rathole systemd service
      copy:
        src: rathole.service
        dest: /etc/systemd/system/rathole.service
        mode: '0644'
        owner: root
        group: root
      notify: reload systemd

    - name: Create rathole SSH systemd service
      copy:
        src: rathole-ssh.service
        dest: /etc/systemd/system/rathole-ssh.service
        mode: '0644'
        owner: root
        group: root
      notify: reload systemd

    - name: rathole service is controlled by storage leader election
      systemd:
        name: rathole
        enabled: no
        daemon_reload: yes

    - name: Enable and start rathole SSH service
      systemd:
        name: rathole-ssh
        enabled: yes
        state: started
        daemon_reload: yes

  handlers:
    - name: reload systemd
      systemd:
        daemon_reload: yes
