---
- name: Install etcd leader election for PostgreSQL and Qdrant
  hosts: storage
  become: yes
  vars:
    etcd_client_port: 2379
    
  tasks:
    - name: Install etcdctl if not present
      apt:
        name: etcd-client
        state: present
        update_cache: yes

    - name: Copy etcd leader election script
      copy:
        src: /etc/ansible/scripts/etcd-leader-election.sh
        dest: /usr/local/bin/etcd-leader-election.sh
        mode: '0755'
      notify: restart cluster leader election

    - name: Create cluster leader election systemd service
      copy:
        dest: /etc/systemd/system/cluster-leader-election.service
        content: |
          [Unit]
          Description=Cluster Leader Election via etcd
          After=network.target etcd.service
          Wants=etcd.service

          [Service]
          Type=simple
          ExecStart=/usr/local/bin/etcd-leader-election.sh "{% for host in groups['storage'] %}http://{{ hostvars[host]['ansible_default_ipv4']['address'] }}:2379{% if not loop.last %},{% endif %}{% endfor %}"
          Restart=always
          RestartSec=5
          User=root

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Enable cluster leader election service
      systemd:
        name: cluster-leader-election.service
        enabled: yes

    - name: Start cluster leader election service
      systemd:
        name: cluster-leader-election.service
        state: started

  handlers:
    - name: restart cluster leader election
      systemd:
        name: cluster-leader-election.service
        state: restarted
