---
- name: Install DHCP leader election
  hosts: core
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name:
          - dnsmasq
          - python3-etcd3
          - python3-netifaces
          - etcd-client
        state: present

    - name: Install python3-scapy without recommends
      apt:
        name: python3-scapy
        state: present
        install_recommends: no

    - name: Copy DHCP server script
      copy:
        src: scripts/dhcp-server.py
        dest: /usr/local/bin/dhcp-server.py
        mode: '0755'
        owner: root
        group: root
      notify: restart dhcp-leader-election

    - name: Copy DHCP leader election script
      copy:
        src: scripts/dhcp-leader-election.sh
        dest: /usr/local/bin/dhcp-leader-election.sh
        mode: '0755'
        owner: root
        group: root
      notify: restart dhcp-leader-election

    - name: Create DHCP server systemd service
      copy:
        dest: /etc/systemd/system/dhcp-server.service
        mode: '0644'
        content: |
          [Unit]
          Description=Scapy-based DHCP Server
          After=network-online.target
          Wants=network-online.target

          [Service]
          Type=simple
          ExecStart=/usr/local/bin/dhcp-server.py
          Restart=always
          RestartSec=5
          User=root
          Environment=ETCD_HOSTS="{% for host in groups['core'] %}http://{{ hostvars[host]['ansible_host'] }}:2379{% if not loop.last %},{% endif %}{% endfor %}"

          [Install]
          WantedBy=multi-user.target

    - name: Create DHCP leader election systemd service
      copy:
        dest: /etc/systemd/system/dhcp-leader-election.service
        mode: '0644'
        content: |
          [Unit]
          Description=DHCP Leader Election via etcd
          After=network-online.target etcd.service
          Wants=etcd.service network-online.target

          [Service]
          Type=simple
          ExecStart=/usr/local/bin/dhcp-leader-election.sh "{% for host in groups['core'] %}http://{{ hostvars[host]['ansible_host'] }}:2379{% if not loop.last %},{% endif %}{% endfor %}"
          Restart=always
          RestartSec=5
          User=root

          [Install]
          WantedBy=multi-user.target

    - name: Create dnsmasq configuration (DNS and TFTP only)
      copy:
        dest: /etc/dnsmasq.d/dns-tftp.conf
        mode: '0644'
        content: |
          # DNS configuration
          local=/xc/
          domain=xc
          domain-needed
          
          # PXE boot configuration
          enable-tftp
          tftp-root=/var/lib/tftpboot
          
          # Disable DHCP (handled by scapy-based server)
          port=53

    - name: Create TFTP root directory
      file:
        path: /var/lib/tftpboot
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: Enable and start dnsmasq service (for DNS and TFTP)
      systemd:
        name: dnsmasq
        enabled: yes
        state: started
        daemon_reload: yes

    - name: Create DHCP server service (disabled, controlled by leader election)
      systemd:
        name: dhcp-server
        enabled: no
        daemon_reload: yes

    - name: Enable DHCP leader election service
      systemd:
        name: dhcp-leader-election
        enabled: yes
        daemon_reload: yes

    - name: Start DHCP leader election service
      systemd:
        name: dhcp-leader-election
        state: started
      register: dhcp_election_start
      changed_when: dhcp_election_start.changed and dhcp_election_start.state != "started"

  handlers:
    - name: restart dhcp-leader-election
      systemd:
        name: dhcp-leader-election
        state: restarted
