---
- name: Install rathole configuration and service
  hosts: core
  become: yes
  vars:
    rathole_binary_path: "/usr/local/bin/rathole"

  tasks:
    - name: Check if rathole binary exists on ansible host
      stat:
        path: /usr/local/bin/rathole
      register: rathole_binary_ansible_host
      delegate_to: localhost

    - name: Fail if rathole binary not found
      fail:
        msg: "Rathole binary not found. Please run build-rathole.yml first."
      when: not rathole_binary_ansible_host.stat.exists

    - name: Copy rathole binary from ansible host
      copy:
        src: /usr/local/bin/rathole
        dest: "{{ rathole_binary_path }}"
        mode: '0755'
        owner: root
        group: root

    - name: Create rathole config directory
      file:
        path: /etc/rathole
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: Install rathole config management script
      copy:
        src: rathole-config.py
        dest: /usr/local/bin/rathole-config
        mode: '0755'
        owner: root
        group: root

    - name: Create rathole client configuration
      template:
        src: rathole-client.toml.j2
        dest: /etc/rathole/client.toml
        mode: '0644'
        owner: root
        group: root

    - name: Create rathole systemd service
      copy:
        src: rathole.service
        dest: /etc/systemd/system/rathole.service
        mode: '0644'
        owner: root
        group: root
      notify: reload systemd

    - name: rathole service is controlled by keepalived
      systemd:
        name: rathole
        enabled: no
        daemon_reload: yes

  handlers:
    - name: reload systemd
      systemd:
        daemon_reload: yes
