---
- name: Add Ceph disk to storage nodes
  hosts: storage
  become: yes
  tasks:
    - name: Check if /dev/mapper/vg0-ceph exists
      stat:
        path: /dev/mapper/vg0-ceph
      register: ceph_disk

    - name: Fail if Ceph disk doesn't exist
      fail:
        msg: "/dev/mapper/vg0-ceph does not exist"
      when: not ceph_disk.stat.exists

    - name: Check if MicroCeph is installed
      command: snap list microceph
      register: microceph_check
      failed_when: false
      changed_when: false

    - name: Fail if MicroCeph is not installed
      fail:
        msg: "MicroCeph is not installed"
      when: microceph_check.rc != 0

    - name: Check if MicroCeph service is running
      command: systemctl is-active snap.microceph.daemon
      register: microceph_service_status
      failed_when: false
      changed_when: false

    - name: Start MicroCeph service if not active
      systemd:
        name: snap.microceph.daemon
        state: started
        enabled: yes
      when: microceph_service_status.stdout != "active"

    - name: Wait for MicroCeph service to be ready
      command: systemctl is-active snap.microceph.daemon
      register: service_check
      until: service_check.stdout == "active"
      retries: 5
      delay: 2
      when: microceph_service_status.stdout != "active"

    - name: Add disk to MicroCeph
      command: microceph disk add /dev/mapper/vg0-ceph
      register: disk_add_result
      failed_when: 
        - disk_add_result.rc != 0
        - "'already exists' not in disk_add_result.stderr"
      changed_when: disk_add_result.rc == 0

    - name: Display disk add result
      debug:
        msg: "{{ disk_add_result.stdout if disk_add_result.stdout else disk_add_result.stderr }}"
