---
- import_playbook: install-dhcp-leader-election.yml

- name: Setup admin services on storage nodes s1-s3
  hosts: s1,s2,s3
  become: yes
  vars:
    admin_services_dir: /opt/admin-services
    
  tasks:
    - name: Install required packages
      apt:
        name:
          - python3-pip
          - python3-flask
          - python3-etcd3
          - python3-grpcio
          - python3-protobuf
          - python3-dnspython
          - dnsmasq
          - nginx
          - ansible-core
          - git
        state: present
        update_cache: yes

    - name: Create admin services directory
      file:
        path: "{{ admin_services_dir }}"
        state: directory
        mode: '0755'

    - name: Clone infrastructure repository
      git:
        repo: "{{ ansible_repo_url | default('https://gitlab.com/devrandom01/xcluster.git') }}"
        dest: /opt/infrastructure
        version: "{{ ansible_repo_branch | default(omit) }}"
        force: yes

    - name: Check if /etc/ansible is already correct symlink
      stat:
        path: /etc/ansible
      register: etc_ansible_stat

    - name: Remove /etc/ansible if it's not the correct symlink
      file:
        path: /etc/ansible
        state: absent
      when: >
        etc_ansible_stat.stat.exists and 
        (not etc_ansible_stat.stat.islnk or 
         etc_ansible_stat.stat.lnk_target != '/opt/infrastructure/config/ansible')

    - name: Create symlink from /etc/ansible to infrastructure config
      file:
        src: /opt/infrastructure/config/ansible
        dest: /etc/ansible
        state: link
      when: >
        not etc_ansible_stat.stat.exists or
        not etc_ansible_stat.stat.islnk or
        etc_ansible_stat.stat.lnk_target != '/opt/infrastructure/config/ansible'


    - name: Detect if running from docker container
      stat:
        path: /data
      register: docker_data_dir
      delegate_to: localhost

    - name: Set file source paths based on environment
      set_fact:
        bootstrap_files_source: "{{ '/data' if docker_data_dir.stat.exists else '/opt/bootstrap-files' }}"

    - name: Ensure bootstrap files directory exists
      file:
        path: /opt/bootstrap-files
        state: directory
        mode: '0755'

    - name: Copy bootstrap files to target node
      copy:
        src: "{{ bootstrap_files_source }}/{{ item }}"
        dest: /opt/bootstrap-files/{{ item }}
        mode: preserve
      loop:
        - ansible_ssh_key
        - ansible_ssh_key.pub

    - name: Copy etcd-based allocation API
      copy:
        src: /opt/infrastructure/config/ansible/files/app_etcd.py
        dest: "{{ admin_services_dir }}/app_etcd.py"
        mode: '0644'
        remote_src: yes
      notify: restart allocation-api

    - name: Copy etcd management scripts to /usr/local/bin
      copy:
        src: "/opt/infrastructure/config/ansible/files/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        mode: '0755'
        remote_src: yes
      loop:
        - populate_local_node.py
        - check_cluster.py
        - lease-manager.py

    - name: Create systemd service for allocation API
      copy:
        dest: /etc/systemd/system/allocation-api.service
        content: |
          [Unit]
          Description=Allocation API Service
          After=network.target etcd.service
          Wants=etcd.service

          [Service]
          Type=simple
          Environment="ETCD_HOSTS={% for h in groups['core'] %}{{ hostvars[h]['ansible_host'] }}:2379{% if not loop.last %},{% endif %}{% endfor %}"
          ExecStart=/usr/bin/python3 {{ admin_services_dir }}/app_etcd.py
          Restart=always
          RestartSec=5
          User=root

          [Install]
          WantedBy=multi-user.target
      notify: restart allocation-api

    - name: Configure nginx as reverse proxy
      copy:
        dest: /etc/nginx/sites-available/allocation-api
        content: |
          server {
              listen 80;
              server_name _;
              
              location /api/ {
                  proxy_pass http://127.0.0.1:12723;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
              }
              
              location /ubuntu/ {
                  alias /var/lib/tftpboot/ubuntu/;
                  autoindex on;
              }
              
              location /autoinstall/ {
                  alias /var/www/html/autoinstall/;
                  autoindex on;
              }
              
              location / {
                  root /var/www/html;
                  index index.html;
              }
          }
      notify: restart nginx

    - name: Enable nginx site
      file:
        src: /etc/nginx/sites-available/allocation-api
        dest: /etc/nginx/sites-enabled/allocation-api
        state: link
      notify: restart nginx

    - name: Remove default nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: restart nginx

    - name: Flush handlers to restart nginx immediately
      meta: flush_handlers

    - name: Disable systemd-resolved to free port 53
      systemd:
        name: systemd-resolved
        state: stopped
        enabled: no

    - name: Check if resolv.conf is a symlink
      stat:
        path: /etc/resolv.conf
      register: resolv_stat

    - name: Remove systemd-resolved symlink
      file:
        path: /etc/resolv.conf
        state: absent
      when: resolv_stat.stat.islnk is defined and resolv_stat.stat.islnk

    - name: Create static resolv.conf
      copy:
        dest: /etc/resolv.conf
        content: |
          nameserver 10.0.0.1
          search xc
        mode: '0644'

    - name: Clear default dnsmasq.conf to avoid conflicts
      copy:
        dest: /etc/dnsmasq.conf
        content: |
          # Main dnsmasq configuration
          # All configuration is in /etc/dnsmasq.d/
          conf-dir=/etc/dnsmasq.d/,*.conf
          # Use additional hosts file for static DNS entries
          addn-hosts=/etc/static-hosts
        backup: yes

    # Note: dnsmasq configuration is handled by the DHCP leader election playbook
    # The leader election service will manage dnsmasq lifecycle

    - name: Create empty static hosts file for dnsmasq
      copy:
        dest: /etc/static-hosts
        content: ""
        force: no
        owner: root
        group: root
        mode: '0644'

    - name: Create TFTP directory structure
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /var/lib/tftpboot
        - /var/lib/tftpboot/EFI
        - /var/lib/tftpboot/EFI/BOOT
        - /var/lib/tftpboot/grub
        - /var/lib/tftpboot/ubuntu

    - name: Check if Ubuntu ISO already exists
      stat:
        path: /var/lib/tftpboot/ubuntu/ubuntu-24.04.2-live-server-amd64.iso
      register: iso_file

    - name: Check if Ubuntu ISO exists on ansible host
      stat:
        path: /var/lib/tftpboot/ubuntu/ubuntu-24.04.2-live-server-amd64.iso
      register: ansible_host_iso
      delegate_to: localhost
      when: not iso_file.stat.exists

    - name: Copy Ubuntu ISO from ansible host
      copy:
        src: /var/lib/tftpboot/ubuntu/ubuntu-24.04.2-live-server-amd64.iso
        dest: /var/lib/tftpboot/ubuntu/ubuntu-24.04.2-live-server-amd64.iso
        mode: '0644'
      when: not iso_file.stat.exists and ansible_host_iso.stat.exists
      register: iso_copy_result

    - name: Download Ubuntu ISO for netboot files (fallback)
      get_url:
        url: http://10.0.0.1/ubuntu-24.04.2-live-server-amd64.iso
        dest: /var/lib/tftpboot/ubuntu/ubuntu-24.04.2-live-server-amd64.iso
        mode: '0644'
      when: not iso_file.stat.exists and (not ansible_host_iso.stat.exists or iso_copy_result is failed)

    - name: Install required packages for EFI extraction
      apt:
        name:
          - genisoimage
        state: present

    - name: Check if netboot files exist
      stat:
        path: "{{ item }}"
      register: netboot_files
      loop:
        - /var/lib/tftpboot/ubuntu/vmlinuz
        - /var/lib/tftpboot/ubuntu/initrd

    - name: Extract netboot files from ISO
      shell: |
        isoinfo -R -x /casper/vmlinuz -i /var/lib/tftpboot/ubuntu/ubuntu-24.04.2-live-server-amd64.iso > /var/lib/tftpboot/ubuntu/vmlinuz
        isoinfo -R -x /casper/initrd -i /var/lib/tftpboot/ubuntu/ubuntu-24.04.2-live-server-amd64.iso > /var/lib/tftpboot/ubuntu/initrd
      when: netboot_files.results | selectattr('stat.exists', 'equalto', false) | list | length > 0

    - name: Check if EFI files already exist
      stat:
        path: "{{ item }}"
      register: efi_files
      loop:
        - /var/lib/tftpboot/EFI/BOOT/bootx64.efi
        - /var/lib/tftpboot/EFI/BOOT/grubx64.efi

    - name: Download and extract EFI boot files
      shell: |
        cd /tmp
        apt-get download shim-signed grub-efi-amd64-signed
        dpkg-deb --fsys-tarfile shim-signed*deb | tar x ./usr/lib/shim/shimx64.efi.signed.latest -O > /var/lib/tftpboot/EFI/BOOT/bootx64.efi
        dpkg-deb --fsys-tarfile grub-efi-amd64-signed*deb | tar x ./usr/lib/grub/x86_64-efi-signed/grubnetx64.efi.signed -O > /var/lib/tftpboot/EFI/BOOT/grubx64.efi
        rm -f shim-signed*.deb grub-efi-amd64-signed*.deb
      when: efi_files.results | selectattr('stat.exists', 'equalto', false) | list | length > 0

    - name: Create grub configuration for PXE boot
      copy:
        dest: /var/lib/tftpboot/grub/grub.cfg
        content: |
          set timeout=30
          set default=0

          menuentry "Boot from First Hard Disk (EFI)" {
              # set root=(hd0,1)
              search --set=root --file /efi/ubuntu/grub.cfg
              configfile /efi/ubuntu/grub.cfg
          }

          menuentry "Ubuntu 24.04 Server Autoinstall" {
              linux /ubuntu/vmlinuz vga=0x31A text nomodeset ip=dhcp url=http://{{ ansible_host }}/ubuntu/ubuntu-24.04.2-live-server-amd64.iso autoinstall ds='nocloud-net;s=http://{{ ansible_host }}/autoinstall/' cloud-config-url=/dev/null
              initrd /ubuntu/initrd
          }
          
          menuentry "Ubuntu 24.04 Server Manual Install" {
              linux /ubuntu/vmlinuz vga=0x31A text nomodeset ip=dhcp url=http://{{ ansible_host }}/ubuntu/ubuntu-24.04.2-live-server-amd64.iso
              initrd /ubuntu/initrd
          }


    - name: Create autoinstall directory
      file:
        path: /var/www/html/autoinstall
        state: directory
        mode: '0755'

    - name: Copy autoinstall user-data
      copy:
        src: /opt/infrastructure/data/autoinstall/user-data
        dest: /var/www/html/autoinstall/user-data
        mode: '0644'
        remote_src: yes

    - name: Copy autoinstall meta-data
      copy:
        src: /opt/infrastructure/data/autoinstall/meta-data
        dest: /var/www/html/autoinstall/meta-data
        mode: '0644'
        remote_src: yes

    - name: Copy ansible SSH public key
      copy:
        src: /opt/bootstrap-files/ansible_ssh_key.pub
        dest: /var/www/html/ansible_ssh_key.pub
        mode: '0644'
        remote_src: yes

    - name: Create .ssh directory for root
      file:
        path: /root/.ssh
        state: directory
        mode: '0700'
        owner: root
        group: root

    - name: Copy ansible SSH private key to s1
      copy:
        src: /opt/bootstrap-files/ansible_ssh_key
        dest: /root/.ssh/id_ed25519
        mode: '0600'
        owner: root
        group: root
        remote_src: yes

    - name: Copy ansible SSH public key to s1 .ssh directory
      copy:
        src: /opt/bootstrap-files/ansible_ssh_key.pub
        dest: /root/.ssh/id_ed25519.pub
        mode: '0644'
        owner: root
        group: root
        remote_src: yes

    - name: Create static hosts update script
      copy:
        dest: /usr/local/bin/update-dhcp-hosts.sh
        mode: '0755'
        content: |
          #!/bin/bash
          # Update static DNS hosts from etcd
          
          TEMP_FILE=$(mktemp)
          HOSTS_FILE="/etc/static-hosts"
          
          if curl -s http://localhost/api/hosts > "$TEMP_FILE" 2>/dev/null; then
              if [ -s "$TEMP_FILE" ]; then
                  # Only reload if the configuration has actually changed
                  if ! cmp -s "$TEMP_FILE" "$HOSTS_FILE"; then
                      echo "DNS hosts configuration changed, updating and reloading dnsmasq"
                      cp "$TEMP_FILE" "$HOSTS_FILE"
                      systemctl reload dnsmasq
                  fi
                  rm -f "$TEMP_FILE"
              else
                  rm -f "$TEMP_FILE"
              fi
          else
              rm -f "$TEMP_FILE"
          fi

    - name: Create dnsmasq configuration directory
      file:
        path: /etc/dnsmasq.d
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: Create dnsmasq configuration (DNS and TFTP only)
      copy:
        dest: /etc/dnsmasq.d/dns-tftp.conf
        mode: '0644'
        content: |
          # DNS configuration
          local=/xc/
          domain=xc
          domain-needed
          
          # PXE boot configuration
          enable-tftp
          tftp-root=/var/lib/tftpboot
          
          # Disable DHCP (handled by scapy-based server)
          port=53

    - name: Enable and start dnsmasq service (for DNS and TFTP)
      systemd:
        name: dnsmasq
        enabled: yes
        state: started
        daemon_reload: yes

    - name: Create systemd timer for DHCP updates
      copy:
        dest: /etc/systemd/system/update-dhcp-hosts.timer
        content: |
          [Unit]
          Description=Update DHCP hosts from etcd
          
          [Timer]
          OnBootSec=30s
          OnUnitActiveSec=30s
          
          [Install]
          WantedBy=timers.target

    - name: Create systemd service for DHCP updates
      copy:
        dest: /etc/systemd/system/update-dhcp-hosts.service
        content: |
          [Unit]
          Description=Update DHCP hosts from etcd
          
          [Service]
          Type=oneshot
          ExecStart=/usr/local/bin/update-dhcp-hosts.sh

    - name: Enable and start services
      systemd:
        name: "{{ item }}"
        enabled: yes
        state: started
        daemon_reload: yes
      loop:
        - allocation-api
        - nginx
        - update-dhcp-hosts.timer

    - name: Wait for etcd to be ready
      wait_for:
        port: 2379
        host: "{{ ansible_host }}"
        timeout: 30

    - name: Populate local node in etcd
      command: "/usr/local/bin/populate_local_node.py"
      environment:
        ETCD_HOST: "{{ ansible_host }}:2379"
      register: populate_result
      changed_when: "'Added node' in populate_result.stdout"

    - name: Display node registration result
      debug:
        var: populate_result.stdout_lines

  handlers:
    - name: restart allocation-api
      systemd:
        name: allocation-api
        state: restarted

    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
