---
- name: Setup storage mountpoints
  hosts: storage
  become: yes
  tasks:
    - name: Create /rbd directory
      file:
        path: /rbd
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: Verify /rbd mountpoint created
      stat:
        path: /rbd
      register: rbd_mountpoint

    - name: Display mountpoint status
      debug:
        msg: "/rbd mountpoint successfully created"
      when: rbd_mountpoint.stat.exists and rbd_mountpoint.stat.isdir

    - name: Configure Ceph RBD client settings for faster failover
      block:
        - name: Set Ceph mon client hunt interval for faster failover
          command: ceph config set client mon_client_hunt_interval 3
          run_once: true
          ignore_errors: yes

        - name: Set OSD heartbeat grace period for faster failure detection
          command: ceph config set osd osd_heartbeat_grace 10
          run_once: true
          ignore_errors: yes

        - name: Set OSD heartbeat interval for faster detection
          command: ceph config set osd osd_heartbeat_interval 3
          run_once: true
          ignore_errors: yes

        - name: Set OSD down out interval for faster recovery
          command: ceph config set mon mon_osd_down_out_interval 30
          run_once: true
          ignore_errors: yes

        - name: Set OSD report timeout for faster failure detection
          command: ceph config set mon mon_osd_report_timeout 15
          run_once: true
          ignore_errors: yes

        - name: Set minimum OSD reporters for faster detection
          command: ceph config set mon mon_osd_min_down_reporters 1
          run_once: true
          ignore_errors: yes

        - name: Set OSD mon heartbeat interval for isolated OSDs
          command: ceph config set osd osd_mon_heartbeat_interval 10
          run_once: true
          ignore_errors: yes

        - name: Set OSD mon report interval for faster reporting
          command: ceph config set osd osd_mon_report_interval 5
          run_once: true
          ignore_errors: yes
      when: inventory_hostname == ansible_play_hosts[0]
