---
- name: Fix Ceph cluster after IP changes
  hosts: storage
  become: yes
  tasks:
    - name: Stop MicroCeph service
      systemd:
        name: snap.microceph.daemon
        state: stopped

    - name: Remove MicroCeph completely
      shell: snap remove microceph --purge
      ignore_errors: yes

    - name: Clean up any remaining MicroCeph data
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/snap/microceph
        - /snap/microceph

    - name: Check if /dev/mapper/vg0-ceph exists
      stat:
        path: /dev/mapper/vg0-ceph
      register: ceph_lv

    - name: Wipe Ceph logical volume
      shell: |
        wipefs -a /dev/mapper/vg0-ceph
        dd if=/dev/zero of=/dev/mapper/vg0-ceph bs=1M count=100
      when: ceph_lv.stat.exists
      ignore_errors: yes

    - name: Install MicroCeph fresh
      shell: snap install microceph

    - name: Wait for snap to settle
      pause:
        seconds: 5

    - name: Display next steps
      debug:
        msg: |
          MicroCeph has been reinstalled on all nodes.
          Now run the following playbooks in order:
          ansible-playbook add-ceph-nodes.yml
          ansible-playbook setup-ceph-disk.yml
          ansible-playbook create-ceph-pool.yml
