services:
  ntp-server:
    image: cturra/ntp:latest
    container_name: ntp-server
    restart: unless-stopped
    network_mode: host
    cap_add:
      - SYS_TIME
    environment:
      - NTP_SERVERS=pool.ntp.org

  dnsmasq:
    build:
      context: ./dnsmasq
    container_name: dnsmasq
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - ./data:/data

  httpd:
    build:
      context: ./httpd
    container_name: http
    restart: unless-stopped
    network_mode: host
    ports:
      - "10.0.0.1:80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data:/usr/share/nginx/html:ro
      - hostname_db:/data

  squid:
    image: ubuntu/squid:latest
    container_name: squid
    restart: unless-stopped
    network_mode: host
    ports:
      - "10.0.0.1:3128:3128"
    volumes:
      - ./config/squid.conf:/etc/squid/squid.conf:ro
      - squid_cache:/var/spool/squid

volumes:
  squid_cache:
  hostname_db:
