---
- name: Install PostgreSQL on core nodes
  hosts: core
  become: yes
  tasks:
    - name: Install PostgreSQL packages
      apt:
        name:
          - postgresql
          - postgresql-contrib
          - python3-psycopg2
        state: present

    - name: Update PostgreSQL data directory in config
      lineinfile:
        path: /etc/postgresql/16/main/postgresql.conf
        regexp: '^#?data_directory\s*='
        line: "data_directory = '/rbd/user/postgres'"
        backup: yes

    - name: Configure PostgreSQL to listen on all addresses
      lineinfile:
        path: /etc/postgresql/16/main/postgresql.conf
        regexp: '^#?listen_addresses\s*='
        line: "listen_addresses = '*'"
        backup: yes

    - name: Configure PostgreSQL client authentication for Docker networks
      lineinfile:
        path: /etc/postgresql/16/main/pg_hba.conf
        line: "host    all             all             172.0.0.0/8             scram-sha-256"
        insertafter: "# IPv4 local connections:"
        backup: yes

    - name: Check if this node is the current storage leader
      uri:
        url: "http://{{ ansible_host }}:5000/api/health"
        method: GET
        timeout: 5
      register: health_check
      failed_when: false
      changed_when: false

    - name: Parse storage leader status
      set_fact:
        is_storage_leader: "{{ (health_check.json.storage_leader | default(false)) if health_check.status == 200 else false }}"

    - name: Disable PostgreSQL service (managed by leader election) - non-leaders only
      systemd:
        name: postgresql
        enabled: no
        state: stopped
      when: not is_storage_leader

    - name: Disable PostgreSQL@16-main service (managed by leader election) - non-leaders only
      systemd:
        name: postgresql@16-main
        enabled: no
        state: stopped
      when: not is_storage_leader

    - name: Disable PostgreSQL service for leader (but keep it running)
      systemd:
        name: postgresql
        enabled: no
      when: is_storage_leader

    - name: Disable PostgreSQL@16-main service for leader (but keep it running)
      systemd:
        name: postgresql@16-main
        enabled: no
      when: is_storage_leader

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes


    - name: Check if PostgreSQL cluster exists
      stat:
        path: /rbd/user/postgres/PG_VERSION
      register: cluster_exists
      when: is_storage_leader
      tags:
        - never
        - init_db

    - name: Initialize PostgreSQL cluster
      become_user: postgres
      shell: |
        /usr/lib/postgresql/16/bin/initdb -D /rbd/user/postgres
      when: is_storage_leader and not cluster_exists.stat.exists
      tags:
        - never
        - init_db

  handlers:
    - name: restart postgresql
      systemd:
        name: postgresql@16-main
        state: restarted
