---
- name: Install Qdrant on core nodes
  hosts: core
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name:
          - curl
          - wget
        state: present

    - name: Check if Qdrant is already installed
      stat:
        path: /opt/qdrant/qdrant
      register: qdrant_installed

    - name: Download Qdrant tar.gz package
      shell: |
        wget -O /tmp/qdrant.tar.gz https://github.com/qdrant/qdrant/releases/download/v1.14.1/qdrant-x86_64-unknown-linux-gnu.tar.gz
        chmod 644 /tmp/qdrant.tar.gz
      when: not qdrant_installed.stat.exists

    - name: Create Qdrant installation directory
      file:
        path: /opt/qdrant
        state: directory
        mode: '0755'
      when: not qdrant_installed.stat.exists

    - name: Extract Qdrant tar.gz package
      unarchive:
        src: /tmp/qdrant.tar.gz
        dest: /opt/qdrant
        remote_src: yes
        owner: root
        group: root
        mode: '0755'
      when: not qdrant_installed.stat.exists

    - name: Create symlink for qdrant binary
      file:
        src: /opt/qdrant/qdrant
        dest: /usr/bin/qdrant
        state: link
      when: not qdrant_installed.stat.exists

    - name: Clean up downloaded tar.gz file
      file:
        path: /tmp/qdrant.tar.gz
        state: absent
      when: not qdrant_installed.stat.exists

    - name: Create qdrant user
      user:
        name: qdrant
        uid: 1001
        system: yes
        shell: /bin/false
        home: /var/lib/qdrant
        create_home: yes

    - name: Create Qdrant configuration directory
      file:
        path: /etc/qdrant
        state: directory
        owner: qdrant
        group: qdrant
        mode: '0755'

    - name: Create Qdrant configuration file
      copy:
        dest: /etc/qdrant/config.yaml
        owner: qdrant
        group: qdrant
        mode: '0644'
        content: |
          storage:
            storage_path: /rbd/user/qdrant/storage
            snapshots_path: /rbd/user/qdrant/snapshots
          service:
            host: 0.0.0.0
            http_port: 6333
            grpc_port: 6334
            static_content_dir: /opt/qdrant/static
          log_level: INFO


    - name: Create Qdrant systemd service
      copy:
        dest: /etc/systemd/system/qdrant.service
        content: |
          [Unit]
          Description=Qdrant Vector Database
          After=network.target

          [Service]
          Type=simple
          User=qdrant
          Group=qdrant
          ExecStart=/usr/bin/qdrant --config-path /etc/qdrant/config.yaml
          Restart=no
          LimitNOFILE=65536

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes


    - name: Check if /rbd/user is mounted (indicates storage leader)
      shell: mountpoint -q /rbd/user
      register: rbd_user_mounted
      failed_when: false
      changed_when: false

    - name: Set storage leader status based on mount
      set_fact:
        is_storage_leader: "{{ rbd_user_mounted.rc == 0 }}"

    - name: Disable Qdrant service (managed by leader election) - non-leaders only
      systemd:
        name: qdrant
        enabled: no
        state: stopped
      when: not is_storage_leader

    - name: Disable Qdrant service for leader (but keep it running)
      systemd:
        name: qdrant
        enabled: no
      when: is_storage_leader

