---
- name: Install PostgreSQL on core nodes
  hosts: core
  become: yes
  tasks:
    - name: Install PostgreSQL packages
      apt:
        name:
          - postgresql
          - postgresql-contrib
          - python3-psycopg2
        state: present

    - name: Install PostgreSQL RBD manager script
      copy:
        src: scripts/postgres-rbd-manager
        dest: /usr/local/bin/postgres-rbd-manager
        mode: '0755'

    - name: Create postgres-rbd systemd service
      copy:
        dest: /etc/systemd/system/postgres-rbd.service
        content: |
          [Unit]
          Description=PostgreSQL with RBD Storage
          After=network.target

          [Service]
          Type=oneshot
          RemainAfterExit=yes
          ExecStart=/usr/local/bin/postgres-rbd-manager start
          ExecStop=/usr/local/bin/postgres-rbd-manager stop
          TimeoutStartSec=300
          TimeoutStopSec=60
          User=root

          [Install]
          WantedBy=multi-user.target

    - name: Update PostgreSQL data directory in config
      lineinfile:
        path: /etc/postgresql/16/main/postgresql.conf
        regexp: '^#?data_directory\s*='
        line: "data_directory = '/rbd/pg/data'"
        backup: yes

    - name: Configure PostgreSQL to listen on all addresses
      lineinfile:
        path: /etc/postgresql/16/main/postgresql.conf
        regexp: '^#?listen_addresses\s*='
        line: "listen_addresses = '*'"
        backup: yes

    - name: Configure PostgreSQL client authentication for Docker networks
      lineinfile:
        path: /etc/postgresql/16/main/pg_hba.conf
        line: "host    all             all             172.0.0.0/8             scram-sha-256"
        insertafter: "# IPv4 local connections:"
        backup: yes

    - name: Check if this node is the current storage leader
      uri:
        url: "http://{{ ansible_host }}:5000/api/health"
        method: GET
        timeout: 5
      register: health_check
      failed_when: false
      changed_when: false

    - name: Parse storage leader status
      set_fact:
        is_storage_leader: "{{ (health_check.json.storage_leader | default(false)) if health_check.status == 200 else false }}"

    - name: Disable PostgreSQL service (managed by leader election) - non-leaders only
      systemd:
        name: postgresql
        enabled: no
        state: stopped
      when: not is_storage_leader

    - name: Disable PostgreSQL@16-main service (managed by leader election) - non-leaders only
      systemd:
        name: postgresql@16-main
        enabled: no
        state: stopped
      when: not is_storage_leader

    - name: Disable PostgreSQL service for leader (but keep it running)
      systemd:
        name: postgresql
        enabled: no
      when: is_storage_leader

    - name: Disable PostgreSQL@16-main service for leader (but keep it running)
      systemd:
        name: postgresql@16-main
        enabled: no
      when: is_storage_leader

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Disable postgres-rbd service (managed by leader election)
      systemd:
        name: postgres-rbd.service
        enabled: no

    - name: Temporarily start postgres-rbd to initialize database
      systemd:
        name: postgres-rbd.service
        state: started
      register: temp_start
      failed_when: false
      when: inventory_hostname == groups['core'][0]
      tags:
        - never
        - init_db

    - name: Check if PostgreSQL cluster exists at /rbd/pg/data
      stat:
        path: /rbd/pg/data/PG_VERSION
      register: cluster_exists
      when: inventory_hostname == groups['core'][0] and temp_start.failed == false
      tags:
        - never
        - init_db

    - name: Initialize PostgreSQL cluster at /rbd/pg/data
      become_user: postgres
      shell: |
        /usr/lib/postgresql/16/bin/initdb -D /rbd/pg/data
      when: inventory_hostname == groups['core'][0] and temp_start.failed == false and not cluster_exists.stat.exists
      tags:
        - never
        - init_db

    - name: Stop temporary postgres-rbd service
      systemd:
        name: postgres-rbd.service
        state: stopped
      when: inventory_hostname == groups['core'][0] and temp_start.failed == false
      tags:
        - never
        - init_db

  handlers:
    - name: restart postgresql
      systemd:
        name: postgresql@16-main
        state: restarted
