---
- name: Setup base infrastructure on storage nodes s1-s3
  hosts: storage:compute
  become: yes
  vars:
    admin_services_dir: /opt/admin-services
    
  tasks:
    - name: Update package cache
      apt:
        cache_valid_time: 3600
      changed_when: false

    - name: Install required packages
      apt:
        name:
          - python3
          - python3-pip
          - python3-flask
          - python3-etcd3
          - python3-scapy
          - python3-requests
          - nginx
          - squid
          - dnsmasq
          - genisoimage
          - keepalived
          - ntp
          - curl
          - wget
          - git
        state: present

    - name: Create admin services directory
      file:
        path: "{{ admin_services_dir }}"
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: Create cluster utilities directory
      file:
        path: /usr/local/lib/cluster
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: Create web root directory
      file:
        path: /var/www/html
        state: directory
        mode: '0755'
        owner: www-data
        group: www-data

    - name: Clone infrastructure repository
      git:
        repo: https://gitlab.com/devrandom01/ycluster.git
        dest: /opt/infrastructure
        force: no
      ignore_errors: yes

    - name: Create minimal wrapper scripts for legacy compatibility
      copy:
        dest: "{{ item.dest }}"
        mode: '0755'
        owner: root
        group: root
        content: "{{ item.content }}"
      loop:
        - dest: '/usr/local/lib/cluster/populate-local-node'
          content: |
            #!/bin/bash
            exec ycluster cluster populate-local-node "$@"
        - dest: '/usr/local/lib/cluster/check-cluster'
          content: |
            #!/bin/bash
            exec ycluster cluster status "$@"
        - dest: '/usr/local/lib/cluster/update-dhcp-hosts'
          content: |
            #!/bin/bash
            exec ycluster dhcp update-hosts "$@"

- name: Storage specific setup
  hosts: storage
  become: yes

  tasks:
    - name: Set ubuntu user password
      user:
        name: ubuntu
        password: "{{ vault_ubuntu_password | password_hash('sha512') }}"
        update_password: always

    - name: Populate local node information in etcd
      command: /usr/local/lib/cluster/populate-local-node
      register: populate_result
      changed_when: "'Node information updated' in populate_result.stdout"
      failed_when: populate_result.rc != 0
